security:
    oauth2:
        client:
            clientId: 523383919868-ds7hpikgfa257dctt9nrojboul145paf.apps.googleusercontent.com
            clientSecret: AtNwuBsH0a6PRfgrUyFOejoo
            accessTokenUri: https://www.googleapis.com/oauth2/v4/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
            pre-established-redirect-uri: http://localhost:8080/login
            registered-redirect-uri: http://localhost:8080/login
            use-current-uri: false
        resource:
            userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo
            preferTokenInfo: false